### PR TITLE
generate_event deprecated

### PR DESCRIPTION
**Pull request by r1k0**

### CODE REVIEW

**Comment by qdrn** [comment]
Hello. Thanks for your interest in Massa!

I believe you forgot to update the `massa-sc-std` version number in `package.json`.

**Comment by r1k0** [comment]
thx for pointing that out, I did another PR for that.

**Comment by r1k0** [comment]
or should I close both and do it again in one single PR?

**Comment by qdrn** [comment]
Better have one PR than two. We try to merge things that "work" and do not require merging an independent PR.

**Pull request closed without merging**
