### PR TITLE
creates issue templates

### PR DESCRIPTION
**Pull request by SlnPons**

### CODE REVIEW

**Comment by qdrn** [comment]
This repo has nothing to do with Thyra. I don't understand why it's part of the issue template. It's confusing.

**Comment by SlnPons** [comment]
> This repo has nothing to do with Thyra. I don't understand why it's part of the issue template. It's confusing.

Indeed it has nothing to do with Thyra. This ticket is just about creating issue templates that we tested on Thyra repo. We decided to use the same templates (for now) on all repos to help the inno team to work faster. 
If you have a problem with that, feel free to tell us :)

**Comment by qdrn** [comment]
I would remove the Thyra part when it's not relevant as it may be confusing.

**Review by qdrn — APPROVED** [review]

**Comment by qdrn** [comment]
LGTM. Merging. Thanks @SlnPons

**Pull request merged**
