### PR TITLE
Set up CI using GitHub Actions

### LINKED ISSUE #11: Set up CI using GitHub Actions

### PR DESCRIPTION
**Pull request by yvan-sraka**
Fix #11

### CODE REVIEW

**Comment by yvan-sraka** [comment]
The switch to a `package-lock.json` rather than a `yarn.lock` should solve the CI issue (unless we change CI to rely on `yarn` rather than `npm`?)

**Review by qdrn — COMMENTED** [review]
Either are fine. We then need to add the corresponding CI tests. But I would rather do that after we fix `massa-sc-scripts` since it will change how things are compiled.

**Review by qdrn — CHANGES_REQUESTED** [review]
Now that we move each example to its own directory this will not work. There are still no tests.

The idea would be to make something that goes through all example directories and tries to build.

**Comment by yvan-sraka** [comment]
> Now that we move each example to its own directory this will not work. There are still no tests.
> 
> The idea would be to make something that goes through all example directories and tries to build.

We could have something that launch `npm test` into each subfolder :)

**Comment by qdrn** [comment]
> > Now that we move each example to its own directory this will not work. There are still no tests.
> > The idea would be to make something that goes through all example directories and tries to build.
> 
> We could have something that launch `npm test` into each subfolder :)

Yes sure. I guess in an ideal world, a "full" test would be building and then executing the SC with the tester. However the tester does not work with autonomous SC so it's not possible.

For now a test could be building all SCs.

**Review by qdrn — CHANGES_REQUESTED** [review]
It does not pass CI as is.

The `package-lock.json` should be removed.

**Comment by qdrn** [comment]
Still does not pass CI...

**Pull request closed without merging**
